"""user oauth  migration.

Revision ID: 228577c97b75
Revises: 42fe22e2314a
Create Date: 2021-11-26 16:22:11.916234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228577c97b75'
down_revision = '42fe22e2314a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_token_secret', sa.String(length=100), nullable=True))
    op.drop_column('user', 'oauth_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_secret', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'oauth_token_secret')
    # ### end Alembic commands ###
