"""language field added to tweet

Revision ID: 52c47d565abd
Revises: 7675b744d17f
Create Date: 2021-12-21 14:33:51.286368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c47d565abd'
down_revision = '7675b744d17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('lang', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'lang')
    # ### end Alembic commands ###
